name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: bump_version
        uses: oflynned/android-version-bump@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '18'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Lint release
        run: ./gradlew lintRelease

      - name: Build Release apk
        run: ./gradlew assembleRelease

      - name: Rename release
        if: success() && github.ref == 'refs/heads/master'
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/aa-torque.apk

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        if: success() && github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          name: ${{ steps.bump_version.outputs.new_tag }}
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/aa-torque.apk

