name: ci
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          
      - name: Build Release apk
        run: ./gradlew lintRelease

  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Restore keystore
        run: echo ${{ secrets.DEBUG_KEYSTORE }} | base64 -d > $HOME/debug.keystore

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          
      - name: Bump version
        id: bump_version
        uses: oflynned/android-version-bump@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Release apk
        run: >
            ./gradlew assembleRelease 
            -Pandroid.injected.signing.store.file=$HOME/debug.keystore 
            -Pandroid.injected.signing.key.alias=androiddebugkey 
            -Pandroid.injected.signing.store.password=android 
            -Pandroid.injected.signing.key.password=android
        
      - name: Rename release
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/aa-torque.apk

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          name: ${{ steps.bump_version.outputs.new_tag }}
          generate_release_notes: true
          draft: true
          files: |
            app/build/outputs/apk/release/aa-torque.apk

